2025-03-06 16:17:43,781 - INFO - Processo iniciado pelo bot.
2025-03-06 16:17:48,260 - ERROR - Ocorreu um erro, imagem capturada e salva no log de desenvolvedor:
2025-03-06 16:18:01,712 - ERROR - Ocorreu um erro, imagem capturada e salva no log de desenvolvedor:
2025-03-06 16:18:06,407 - ERROR - Erro ao preencher cotação dos correios: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-03-06 16:18:22,774 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59689): Max retries exceeded with url: /session/0ff95ca69bcdbcbfa3f6c63d40a947d1/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020C78558050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:18:39,104 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59689): Max retries exceeded with url: /session/0ff95ca69bcdbcbfa3f6c63d40a947d1/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020C785C4C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:18:55,469 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59689): Max retries exceeded with url: /session/0ff95ca69bcdbcbfa3f6c63d40a947d1/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020C78551B80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:19:11,730 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59689): Max retries exceeded with url: /session/0ff95ca69bcdbcbfa3f6c63d40a947d1/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020C785523F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:19:27,949 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59689): Max retries exceeded with url: /session/0ff95ca69bcdbcbfa3f6c63d40a947d1/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020C78552C60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:19:44,354 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59689): Max retries exceeded with url: /session/0ff95ca69bcdbcbfa3f6c63d40a947d1/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020C785526C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:20:00,704 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59689): Max retries exceeded with url: /session/0ff95ca69bcdbcbfa3f6c63d40a947d1/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020C785519A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:20:00,767 - ERROR - Ocorreu um erro, imagem capturada e salva no log de desenvolvedor:
